/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbapplication;

import javax.swing.JMenuItem;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author 15202607
 */
public class TelaInicial extends javax.swing.JFrame implements InternalFrameListener{
    boolean flagCadGenero = false;
    boolean flagCadJogo = false;
    boolean flagCadPlataforma = false;
    boolean flagCadProdutora = false;
    boolean flagAltGenero = false;
    boolean flagAltJogo = false;
    boolean flagAltPlataforma = false;
    boolean flagAltProdutora = false;
    boolean flagDelGenero = false;
    boolean flagDelJogo = false;
    boolean flagDelPlataforma = false;
    boolean flagDelProdutora = false;
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAreaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiGenero = new javax.swing.JMenuItem();
        jmiJogo = new javax.swing.JMenuItem();
        jmiPlataforma = new javax.swing.JMenuItem();
        jmiProdutora = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiAlteraGenero = new javax.swing.JMenuItem();
        jmiAlteraJogo = new javax.swing.JMenuItem();
        jmiAlteraPlataforma = new javax.swing.JMenuItem();
        jmiAlteraProdutora = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiDeletaGenero = new javax.swing.JMenuItem();
        jmiDeletaJogo = new javax.swing.JMenuItem();
        jmiDeletaPlataforma = new javax.swing.JMenuItem();
        jmiDeletaProdutora = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiBuscaGenero = new javax.swing.JMenuItem();
        jmiBuscaJogo = new javax.swing.JMenuItem();
        jmiBuscaPlataforma = new javax.swing.JMenuItem();
        jmiBuscaProdutora = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmCadastro.setText("Cadastros");

        jmiGenero.setText("Gênero");
        jmiGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGeneroActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiGenero);

        jmiJogo.setText("Jogo");
        jmCadastro.add(jmiJogo);

        jmiPlataforma.setText("Plataforma");
        jmCadastro.add(jmiPlataforma);

        jmiProdutora.setText("Produtora");
        jmCadastro.add(jmiProdutora);

        jMenuBar1.add(jmCadastro);

        jMenu2.setText("Alterações");

        jmiAlteraGenero.setText("Gênero");
        jMenu2.add(jmiAlteraGenero);

        jmiAlteraJogo.setText("Jogo");
        jMenu2.add(jmiAlteraJogo);

        jmiAlteraPlataforma.setText("Plataforma");
        jMenu2.add(jmiAlteraPlataforma);

        jmiAlteraProdutora.setText("Produtora");
        jMenu2.add(jmiAlteraProdutora);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Deleções");

        jmiDeletaGenero.setText("Gênero");
        jMenu3.add(jmiDeletaGenero);

        jmiDeletaJogo.setText("Jogo");
        jMenu3.add(jmiDeletaJogo);

        jmiDeletaPlataforma.setText("Plataforma");
        jMenu3.add(jmiDeletaPlataforma);

        jmiDeletaProdutora.setText("Produtora");
        jMenu3.add(jmiDeletaProdutora);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Pesquisar");

        jmiBuscaGenero.setText("Gênero");
        jMenu1.add(jmiBuscaGenero);

        jmiBuscaJogo.setText("Jogo");
        jMenu1.add(jmiBuscaJogo);

        jmiBuscaPlataforma.setText("Plataforma");
        jMenu1.add(jmiBuscaPlataforma);

        jmiBuscaProdutora.setText("Produtora");
        jMenu1.add(jmiBuscaProdutora);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Sair");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirCadGenero() {
        if (!flagCadGenero) {
            GenerosGUI gcad = new GenerosGUI();
            jAreaTrabalho.add(gcad);
            gcad.setVisible(true);
            flagCadGenero = true;
            gcad.addInternalFrameListener(this);
        }
    }
    
    private void jmiGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGeneroActionPerformed
        abrirCadGenero();
    }//GEN-LAST:event_jmiGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenuItem jmiAlteraGenero;
    private javax.swing.JMenuItem jmiAlteraJogo;
    private javax.swing.JMenuItem jmiAlteraPlataforma;
    private javax.swing.JMenuItem jmiAlteraProdutora;
    private javax.swing.JMenuItem jmiBuscaGenero;
    private javax.swing.JMenuItem jmiBuscaJogo;
    private javax.swing.JMenuItem jmiBuscaPlataforma;
    private javax.swing.JMenuItem jmiBuscaProdutora;
    private javax.swing.JMenuItem jmiDeletaGenero;
    private javax.swing.JMenuItem jmiDeletaJogo;
    private javax.swing.JMenuItem jmiDeletaPlataforma;
    private javax.swing.JMenuItem jmiDeletaProdutora;
    private javax.swing.JMenuItem jmiGenero;
    private javax.swing.JMenuItem jmiJogo;
    private javax.swing.JMenuItem jmiPlataforma;
    private javax.swing.JMenuItem jmiProdutora;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent e) {
        if (e.getInternalFrame() instanceof GenerosGUI) {
            flagCadGenero = false;
        } 
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent e) {
        
    }
}
