/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.ProdutoraDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Produtora;

/**
 *
 * @author Alan Quadros <alanquaros@hotmail.com>
 */
public class AltProdutorasGUI extends javax.swing.JInternalFrame {

     DefaultTableModel dtm = new DefaultTableModel(
             new Object[][]{},
             new Object[]{"Código", "Nome", "País de Origem", "Site"}) {
                  @Override
                  public boolean isCellEditable(int row, int column) {
                       return false;
                  }
             };

     /**
      * Creates new form AltProdutorasGUI
      */
     public AltProdutorasGUI() {
          initComponents();
          preencherTabela();
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jPanel1 = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          jtableProdutoras = new javax.swing.JTable();
          jLabel1 = new javax.swing.JLabel();
          jtCodigo = new javax.swing.JTextField();
          jLabel2 = new javax.swing.JLabel();
          jtNome = new javax.swing.JTextField();
          jLabel3 = new javax.swing.JLabel();
          jtPais = new javax.swing.JTextField();
          jLabel4 = new javax.swing.JLabel();
          jtSite = new javax.swing.JTextField();
          jbAlterar = new javax.swing.JButton();
          jbDeletar = new javax.swing.JButton();

          jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

          jtableProdutoras.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Código", "Nome", "País de Origem", "Site"
               }
          ) {
               boolean[] canEdit = new boolean [] {
                    false, true, true, false
               };

               public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
               }
          });
          jtableProdutoras.getTableHeader().setReorderingAllowed(false);
          jtableProdutoras.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseReleased(java.awt.event.MouseEvent evt) {
                    jtableProdutorasMouseReleased(evt);
               }
          });
          jScrollPane1.setViewportView(jtableProdutoras);
          if (jtableProdutoras.getColumnModel().getColumnCount() > 0) {
               jtableProdutoras.getColumnModel().getColumn(0).setMaxWidth(70);
               jtableProdutoras.getColumnModel().getColumn(3).setMinWidth(200);
          }

          jLabel1.setText("Código");

          jLabel2.setText("Nome");

          jLabel3.setText("País de Origem");

          jLabel4.setText("Site");

          jbAlterar.setText("Alterar");
          jbAlterar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jbAlterarActionPerformed(evt);
               }
          });

          jbDeletar.setText("Deletar");
          jbDeletar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jbDeletarActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jtSite)
                         .addComponent(jScrollPane1)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel2))
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel4)))
                              .addGap(0, 18, Short.MAX_VALUE)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel3)
                                   .addComponent(jtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap())
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(212, 212, 212)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)
                    .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(jLabel2)
                         .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jtSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jbAlterar)
                         .addComponent(jbDeletar))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
          try {
               ProdutoraDAO pDAO = new ProdutoraDAO();
               Produtora pro = pDAO.getProdutora(Long.parseLong(jtCodigo.getText()));
               
               pro.setId(Long.parseLong(jtCodigo.getText()));
               pro.setNome(jtNome.getText());
               pro.setPais(jtPais.getText());
               pro.setSite(jtSite.getText());
               
               String sId = (String) jtableProdutoras.getValueAt(jtableProdutoras.getSelectedRow(), 0);
               long id = Long.parseLong(sId);
               
               pDAO.updateProdutora(pro, id);
               JOptionPane.showMessageDialog(null, "Produtora atualizada com sucesso!");
          } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Erro ao atualizar a produtora!\n"+e.getMessage());
          }
          limpar();
          preencherTabela();
     }//GEN-LAST:event_jbAlterarActionPerformed

     private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
          try {
               ProdutoraDAO pDAO = new ProdutoraDAO();
               Produtora pro = pDAO.getProdutora(Long.parseLong(jtCodigo.getText()));
               pDAO.deletarProdutora(pro);
               JOptionPane.showMessageDialog(null, "Produtora deletada com sucesso!");
               
          } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Erro ao deletar produtora\n"+e.getMessage());
          }
          limpar();
          preencherTabela();
     }//GEN-LAST:event_jbDeletarActionPerformed

     private void jtableProdutorasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableProdutorasMouseReleased
          pegarProdutora();
     }//GEN-LAST:event_jtableProdutorasMouseReleased

     private void preencherTabela() {
          try {
               List<Produtora> produtoras = new ArrayList<>();
               ProdutoraDAO pDAo = new ProdutoraDAO();
               produtoras = pDAo.getListaPlataforma();

               for (int i = 0; i < produtoras.size(); i++) {
                    dtm.addRow(new String[]{
                         String.valueOf(produtoras.get(i).getId()),
                         String.valueOf(produtoras.get(i).getNome()),
                         String.valueOf(produtoras.get(i).getPais()),
                         String.valueOf(produtoras.get(i).getSite())
                    });
               }
               jtableProdutoras.setModel(dtm);
               jtableProdutoras.getColumnModel().getColumn(0).setMaxWidth(70);
               jtableProdutoras.getColumnModel().getColumn(3).setMinWidth(200);

          } catch (Exception e) {
               JOptionPane.showMessageDialog(this,
                       "Erro\n" + e.getMessage(),
                       "ERRO",
                       JOptionPane.ERROR_MESSAGE);
          }
     }

     private void pegarProdutora() {
          int linha = jtableProdutoras.getSelectedRow();

          if (linha == -1) {
               JOptionPane.showMessageDialog(this,
                       "Selecione um cliente!",
                       "ERRO",
                       JOptionPane.ERROR_MESSAGE);
          } else {
               jtCodigo.setText((String) jtableProdutoras.getValueAt(linha, 0));
               jtNome.setText((String) jtableProdutoras.getValueAt(linha, 1));
               jtPais.setText((String) jtableProdutoras.getValueAt(linha, 2));
               jtSite.setText((String) jtableProdutoras.getValueAt(linha, 3));
          }
     }
     
     private void limpar(){
          jtCodigo.setText(null);
          jtNome.setText(null);
          jtPais.setText(null);
          jtSite.setText(null);
          dtm.setNumRows(0);
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JButton jbAlterar;
     private javax.swing.JButton jbDeletar;
     private javax.swing.JTextField jtCodigo;
     private javax.swing.JTextField jtNome;
     private javax.swing.JTextField jtPais;
     private javax.swing.JTextField jtSite;
     private javax.swing.JTable jtableProdutoras;
     // End of variables declaration//GEN-END:variables
}
