/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.PlataformaDAO;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Plataforma;

/**
 *
 * @author Alan Quadros <alanquaros@hotmail.com>
 */
public class AltPlataformasGUI extends javax.swing.JInternalFrame {

     DefaultTableModel dtm = new DefaultTableModel(
             new Object[][]{},
             new Object[]{"Código", "Nome", "Tipo", "Fabricante", "Data de Lançamento"}) {
                  @Override
                  public boolean isCellEditable(int row, int column) {
                       return false;
                  }
             };

     public AltPlataformasGUI() {
          initComponents();
          preencherTabela();
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jPanel1 = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          jtablePlataformas = new javax.swing.JTable();
          jLabel1 = new javax.swing.JLabel();
          jtCodPlataforma = new javax.swing.JTextField();
          jLabel2 = new javax.swing.JLabel();
          jtNomePlataforma = new javax.swing.JTextField();
          jLabel3 = new javax.swing.JLabel();
          jtTipo = new javax.swing.JTextField();
          jLabel4 = new javax.swing.JLabel();
          jtFabricante = new javax.swing.JTextField();
          jLabel5 = new javax.swing.JLabel();
          jtDataLancamento = new javax.swing.JTextField();
          jbAlterar = new javax.swing.JButton();
          jbDeletar = new javax.swing.JButton();

          setClosable(true);
          setTitle("Alteração de Plataformas");

          jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

          jtablePlataformas.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null}
               },
               new String [] {
                    "Código", "Nome", "Tipo", "Fabricante", "Data de Lançamento"
               }
          ) {
               boolean[] canEdit = new boolean [] {
                    false, true, true, true, true
               };

               public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
               }
          });
          jtablePlataformas.getTableHeader().setReorderingAllowed(false);
          jtablePlataformas.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseReleased(java.awt.event.MouseEvent evt) {
                    jtablePlataformasMouseReleased(evt);
               }
          });
          jScrollPane1.setViewportView(jtablePlataformas);
          if (jtablePlataformas.getColumnModel().getColumnCount() > 0) {
               jtablePlataformas.getColumnModel().getColumn(0).setPreferredWidth(70);
               jtablePlataformas.getColumnModel().getColumn(0).setMaxWidth(100);
          }

          jLabel1.setText("Código");

          jLabel2.setText("Nome");

          jLabel3.setText("Tipo");

          jLabel4.setText("Fabricante");

          jLabel5.setText("Data de Lançamento");

          jbAlterar.setText("Alterar");
          jbAlterar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jbAlterarActionPerformed(evt);
               }
          });

          jbDeletar.setText("Deletar");
          jbDeletar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jbDeletarActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addComponent(jScrollPane1)
                              .addContainerGap())
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(9, 9, 9)
                              .addComponent(jLabel1)
                              .addGap(97, 97, 97)
                              .addComponent(jLabel2)
                              .addGap(162, 162, 162)
                              .addComponent(jLabel3)
                              .addGap(146, 146, 146)
                              .addComponent(jLabel4)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jLabel5)
                              .addGap(23, 23, 23))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtCodPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jtNomePlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(257, 257, 257)
                                        .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addGap(18, 18, 18)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                        .addComponent(jtDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41))
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(jLabel2)
                         .addComponent(jLabel3)
                         .addComponent(jLabel4)
                         .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jtCodPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jtNomePlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jtDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jbAlterar)
                         .addComponent(jbDeletar))
                    .addContainerGap(16, Short.MAX_VALUE))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void preencherTabela(){
          try {
               List<Plataforma> plataformas = new ArrayList<Plataforma>();
               PlataformaDAO pDAO = new PlataformaDAO();
               plataformas = pDAO.getListaPlataforma();
               
               for (int i = 0; i < plataformas.size(); i++) {
                    dtm.addRow(new String[]{
                         String.valueOf(plataformas.get(i).getIdPlataforma()),
                         String.valueOf(plataformas.get(i).getNomePlataforma()),
                         String.valueOf(plataformas.get(i).getTipoPlataforma()),
                         String.valueOf(plataformas.get(i).getFabricante()),
                         String.valueOf(plataformas.get(i).getDataLancamento())
                    });
               }
               jtablePlataformas.setModel(dtm);
               jtablePlataformas.getColumnModel().getColumn(0).setMaxWidth(70);
               
          } catch (Exception e) {
               JOptionPane.showMessageDialog(this,
                    "Erro\n" + e.getMessage(),
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE);
          }
     }
     
     private void pegarPlataforma(){
          int linha = jtablePlataformas.getSelectedRow();
          
          if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um cliente!",
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            jtCodPlataforma.setText((String) jtablePlataformas.getValueAt(linha, 0));
            jtNomePlataforma.setText((String) jtablePlataformas.getValueAt(linha, 1));
            jtTipo.setText((String) jtablePlataformas.getValueAt(linha, 2));
            jtFabricante.setText((String) jtablePlataformas.getValueAt(linha, 3));
            jtDataLancamento.setText((String) jtablePlataformas.getValueAt(linha, 4));
        }
     }
     
     private void limpar(){
          dtm.setNumRows(0);
          jtCodPlataforma.setText(null);
          jtDataLancamento.setText(null);
          jtFabricante.setText(null);
          jtNomePlataforma.setText(null);
          jtTipo.setText(null);
     }
     
     private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
          try {
               PlataformaDAO pDAO = new PlataformaDAO();
               Plataforma pla = pDAO.getPlataformas(Long.parseLong(jtCodPlataforma.getText()));
               
               pla.setIdPlataforma(Long.parseLong(jtCodPlataforma.getText()));
               pla.setNomePlataforma(jtNomePlataforma.getText());
               pla.setTipoPlataforma(jtTipo.getText());
               pla.setFabricante(jtFabricante.getText());
               pla.setDataLancamento(Date.valueOf(jtDataLancamento.getText()));
               
               String sId = (String) jtablePlataformas.getValueAt(jtablePlataformas.getSelectedRow(), 0);
               long id = Long.parseLong(sId);
               
               pDAO.updatePlataforma(pla, id);
               JOptionPane.showMessageDialog(null, "Plataforma atualizada com sucesso!");
          } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Erro ao atualizar a plataforma!\n"+e.getMessage());
          }
          limpar();
          preencherTabela();
     }//GEN-LAST:event_jbAlterarActionPerformed

     private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
          try {
               PlataformaDAO pDAO = new PlataformaDAO();
               Plataforma pla = pDAO.getPlataformas(Long.parseLong(jtCodPlataforma.getText()));
               
               pDAO.deletarPlataforma(pla);
               JOptionPane.showMessageDialog(null, "Plataforma deletada com sucesso!");
               
          } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Erro ao deletar plataforma\n"+e.getMessage());
          }
          limpar();
          preencherTabela();
     }//GEN-LAST:event_jbDeletarActionPerformed

     private void jtablePlataformasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablePlataformasMouseReleased
          pegarPlataforma();
     }//GEN-LAST:event_jtablePlataformasMouseReleased


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JButton jbAlterar;
     private javax.swing.JButton jbDeletar;
     private javax.swing.JTextField jtCodPlataforma;
     private javax.swing.JTextField jtDataLancamento;
     private javax.swing.JTextField jtFabricante;
     private javax.swing.JTextField jtNomePlataforma;
     private javax.swing.JTextField jtTipo;
     private javax.swing.JTable jtablePlataformas;
     // End of variables declaration//GEN-END:variables
}
