/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.JogoDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Jogo;

/**
 *
 * @author Alan Quadros <alanquaros@hotmail.com>
 */
public class BuscaJogoEMetacritica extends javax.swing.JInternalFrame {

     DefaultTableModel dtm = new DefaultTableModel(
             new Object[][]{},
             new Object[]{"Nome", "Metacrítica"}) {
                  @Override
                  public boolean isCellEditable(int row, int column) {
                       return false;
                  }
             };
     
     /**
      * Creates new form BuscaJogoEMetacritica
      */
     public BuscaJogoEMetacritica() {
          initComponents();
          tabelaJogo();
          
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jPanel1 = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          jtableJogo = new javax.swing.JTable();

          setClosable(true);
          setTitle("Jogo e Metacrítica");

          jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

          jtableJogo.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null},
                    {null, null},
                    {null, null},
                    {null, null}
               },
               new String [] {
                    "Nome", "Metacrítica"
               }
          ) {
               boolean[] canEdit = new boolean [] {
                    false, true
               };

               public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
               }
          });
          jtableJogo.getTableHeader().setReorderingAllowed(false);
          jScrollPane1.setViewportView(jtableJogo);
          if (jtableJogo.getColumnModel().getColumnCount() > 0) {
               jtableJogo.getColumnModel().getColumn(0).setMinWidth(300);
          }

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                    .addContainerGap())
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void tabelaJogo(){
          try {
               List<Jogo> jogos = new ArrayList<>();
               JogoDAO jDAO = new JogoDAO();
               jogos = jDAO.getListaJogo();

               for (int i = 0; i < jogos.size(); i++) {
                    dtm.addRow(new String[]{
                         String.valueOf(jogos.get(i).getNomeJogo()),
                         String.valueOf(jogos.get(i).getMetacritica())
                    });
               }
               jtableJogo.setModel(dtm);
               jtableJogo.getColumnModel().getColumn(0).setMinWidth(300);
          } catch (Exception e) {
               JOptionPane.showMessageDialog(this,
                       "Erro\n" + e.getMessage(),
                       "ERRO",
                       JOptionPane.ERROR_MESSAGE);
          }
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JPanel jPanel1;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTable jtableJogo;
     // End of variables declaration//GEN-END:variables
}
