/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.GeneroDAO;
import dao.JogoDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Genero;
import modelo.Jogo;

/**
 *
 * @author Alan Quadros <alanquaros@hotmail.com>
 */
public class BuscaJogoPlataformaGeneroGUI extends javax.swing.JInternalFrame {

     DefaultTableModel dtm = new DefaultTableModel(
             new Object[][]{},
             new Object[]{"Nome", "Plataforma"}) {
                  @Override
                  public boolean isCellEditable(int row, int column) {
                       return false;
                  }
             };
     
     /**
      * Creates new form BuscaJogoPlataformaGenero
      */
     public BuscaJogoPlataformaGeneroGUI() {
          initComponents();
          preencherComboGenero();
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jPanel1 = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          jcomboGenero = new javax.swing.JComboBox();
          jbBuscar = new javax.swing.JButton();
          jScrollPane1 = new javax.swing.JScrollPane();
          jtableJogo = new javax.swing.JTable();

          setClosable(true);
          setTitle("Busca Jogo e Plataforma por Gênero");

          jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

          jLabel1.setText("Gênero");

          jcomboGenero.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseReleased(java.awt.event.MouseEvent evt) {
                    jcomboGeneroMouseReleased(evt);
               }
          });

          jbBuscar.setText("Buscar");
          jbBuscar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jbBuscarActionPerformed(evt);
               }
          });

          jtableJogo.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {

               },
               new String [] {
                    "Nome", "Plataforma"
               }
          ));
          jtableJogo.getTableHeader().setReorderingAllowed(false);
          jScrollPane1.setViewportView(jtableJogo);
          if (jtableJogo.getColumnModel().getColumnCount() > 0) {
               jtableJogo.getColumnModel().getColumn(0).setMinWidth(200);
          }

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addComponent(jLabel1)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jcomboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(jbBuscar)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(jcomboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jbBuscar))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
          try {
               List<Jogo> jogos = new ArrayList<>();
               JogoDAO jDAO = new JogoDAO();
               
               String query = (String) jcomboGenero.getSelectedItem();
               jogos = jDAO.jogoEPlataformaPorGenero(query);
               
               if(jcomboGenero.getSelectedIndex() == 0){
                    JOptionPane.showMessageDialog(null, "SELECIONE ALGUM GÊNERO!");
               }
               
               for (int i = 0; i < jogos.size(); i++) {
                    dtm.addRow(new String[]{
                         String.valueOf(jogos.get(i).getNomeJogo()),
                         String.valueOf(jogos.get(i).getPlataforma().getNomePlataforma())
                    });
               }
               jtableJogo.setModel(dtm);
               jtableJogo.getColumnModel().getColumn(0).setMinWidth(200);
               
          } catch (Exception e) {
               JOptionPane.showMessageDialog(this,
                       "Erro\n" + e.getMessage(),
                       "ERRO",
                       JOptionPane.ERROR_MESSAGE);
               e.printStackTrace();
          }
     }//GEN-LAST:event_jbBuscarActionPerformed

     private void jcomboGeneroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcomboGeneroMouseReleased
          limpar();
     }//GEN-LAST:event_jcomboGeneroMouseReleased

     private void preencherComboGenero() {
          try {
               List<Genero> generos = new ArrayList<>();
               GeneroDAO gDAO = new GeneroDAO();
               generos = gDAO.getListaGenero();

               jcomboGenero.addItem("--Selecione--");
               for (int i = 0; i < generos.size(); i++) {
                    jcomboGenero.addItem(generos.get(i).toString());
               }

          } catch (Exception e) {
               JOptionPane.showMessageDialog(this,
                       "Erro\n" + e.getMessage(),
                       "ERRO",
                       JOptionPane.ERROR_MESSAGE);
          }
     }
     
     public void limpar(){
          dtm.setNumRows(0);
          jcomboGenero.setSelectedIndex(0);
     }
     
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel jLabel1;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JButton jbBuscar;
     private javax.swing.JComboBox jcomboGenero;
     private javax.swing.JTable jtableJogo;
     // End of variables declaration//GEN-END:variables
}
