/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JMenuItem;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author 15202607
 */
public class TelaInicial extends javax.swing.JFrame implements InternalFrameListener{
    boolean flagCadGenero = false;
    boolean flagAltGenero = false;
    boolean flagCadPlataforma = false;
    boolean flagAltPlataforma = false;
    boolean flagCadProdutora = false;
    boolean flagAltProdutoras = false;
    boolean flagCadJogo = false;
    boolean flagAltJogo = false;
    boolean flagJogoPlataforma = false;
    
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jMenuItem1 = new javax.swing.JMenuItem();
          jAreaTrabalho = new javax.swing.JDesktopPane();
          jMenuBar1 = new javax.swing.JMenuBar();
          jmCadastro = new javax.swing.JMenu();
          jmiGenero = new javax.swing.JMenuItem();
          jMenuItem3 = new javax.swing.JMenuItem();
          jMenuItem4 = new javax.swing.JMenuItem();
          jMenuItem2 = new javax.swing.JMenuItem();
          jMenu2 = new javax.swing.JMenu();
          jMenuItem5 = new javax.swing.JMenuItem();
          jMenuItem7 = new javax.swing.JMenuItem();
          jMenuItem8 = new javax.swing.JMenuItem();
          jMenuItem6 = new javax.swing.JMenuItem();
          jMenu1 = new javax.swing.JMenu();
          jMenuItem9 = new javax.swing.JMenuItem();

          jMenuItem1.setText("jMenuItem1");

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jmCadastro.setText("Cadastros");

          jmiGenero.setText("Gênero");
          jmiGenero.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jmiGeneroActionPerformed(evt);
               }
          });
          jmCadastro.add(jmiGenero);

          jMenuItem3.setText("Plataforma");
          jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem3ActionPerformed(evt);
               }
          });
          jmCadastro.add(jMenuItem3);

          jMenuItem4.setText("Produtora");
          jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem4ActionPerformed(evt);
               }
          });
          jmCadastro.add(jMenuItem4);

          jMenuItem2.setText("Jogo");
          jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem2ActionPerformed(evt);
               }
          });
          jmCadastro.add(jMenuItem2);

          jMenuBar1.add(jmCadastro);

          jMenu2.setText("Alterações");

          jMenuItem5.setText("Gênero");
          jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem5ActionPerformed(evt);
               }
          });
          jMenu2.add(jMenuItem5);

          jMenuItem7.setText("Plataforma");
          jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem7ActionPerformed(evt);
               }
          });
          jMenu2.add(jMenuItem7);

          jMenuItem8.setText("Produtora");
          jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem8ActionPerformed(evt);
               }
          });
          jMenu2.add(jMenuItem8);

          jMenuItem6.setText("Jogo");
          jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem6ActionPerformed(evt);
               }
          });
          jMenu2.add(jMenuItem6);

          jMenuBar1.add(jMenu2);

          jMenu1.setText("Buscas");

          jMenuItem9.setText("Jogos por Plataformas");
          jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem9ActionPerformed(evt);
               }
          });
          jMenu1.add(jMenuItem9);

          jMenuBar1.add(jMenu1);

          setJMenuBar(jMenuBar1);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 1161, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

    private void abrirCadGenero() {
        if (!flagCadGenero) {
            CadGenerosGUI gcad = new CadGenerosGUI();
            jAreaTrabalho.add(gcad);
            gcad.setVisible(true);
            flagCadGenero = true;
            gcad.addInternalFrameListener(this);
        }
    }
    
    private void abrirCadPlataforma() {
        if (!flagCadPlataforma) {
            CadPlataformasGUI cpla = new CadPlataformasGUI();
            jAreaTrabalho.add(cpla);
            cpla.setVisible(true);
            flagCadPlataforma = true;
            cpla.addInternalFrameListener(this);
        }
    }
    
    private void abrirCadJogo() {
        if (!flagCadJogo) {
            CadJogosGUI jcad = new CadJogosGUI();
            jAreaTrabalho.add(jcad);
            jcad.setVisible(true);
            flagCadJogo = true;
            jcad.addInternalFrameListener(this);
        }
    }
    
    private void abrirCadProdutora() {
        if (!flagCadProdutora) {
            CadProdutoraGUI jcad = new CadProdutoraGUI();
            jAreaTrabalho.add(jcad);
            jcad.setVisible(true);
            flagCadProdutora = true;
            jcad.addInternalFrameListener(this);
        }
    }
    
    private void abrirAltGenero() {
        if (!flagAltGenero) {
            AltGenerosGUI gAlt = new AltGenerosGUI();
            jAreaTrabalho.add(gAlt);
            gAlt.setVisible(true);
            flagAltGenero = true;
            gAlt.addInternalFrameListener(this);
        }
    }
    
    private void abrirAltPlataforma(){
         if(!flagAltPlataforma){
              AltPlataformasGUI alp = new AltPlataformasGUI();
              jAreaTrabalho.add(alp);
              alp.setVisible(true);
              flagAltGenero = true;
              alp.addInternalFrameListener(this);
         }
    }
    
    private void abrirAltProdutoras(){
         if(!flagAltProdutoras){
              AltProdutorasGUI alp = new AltProdutorasGUI();
              jAreaTrabalho.add(alp);
              alp.setVisible(true);
              flagAltProdutoras = true;
              alp.addInternalFrameListener(this);
         }
    }
    
    private void abrirAltJogos(){
         if(!flagAltJogo){
              AltJogosGUI alp = new AltJogosGUI();
              jAreaTrabalho.add(alp);
              alp.setVisible(true);
              flagAltJogo = true;
              alp.addInternalFrameListener(this);
         }
    }
    
    private void abrirJogoPlataforma(){
         if(!flagJogoPlataforma){
              BuscaJogoPlataformaGUI alp = new BuscaJogoPlataformaGUI();
              jAreaTrabalho.add(alp);
              alp.setVisible(true);
              flagJogoPlataforma = true;
              alp.addInternalFrameListener(this);
         }
    }
    
    private void jmiGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGeneroActionPerformed
        abrirCadGenero();
    }//GEN-LAST:event_jmiGeneroActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        abrirCadJogo();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        abrirAltGenero();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

     private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
          abrirCadPlataforma();
     }//GEN-LAST:event_jMenuItem3ActionPerformed

     private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
          abrirAltPlataforma();
     }//GEN-LAST:event_jMenuItem7ActionPerformed

     private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
          abrirCadProdutora();
     }//GEN-LAST:event_jMenuItem4ActionPerformed

     private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
          abrirAltProdutoras();
     }//GEN-LAST:event_jMenuItem8ActionPerformed

     private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
          abrirAltJogos();
     }//GEN-LAST:event_jMenuItem6ActionPerformed

     private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
          abrirJogoPlataforma();
     }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JDesktopPane jAreaTrabalho;
     private javax.swing.JMenu jMenu1;
     private javax.swing.JMenu jMenu2;
     private javax.swing.JMenuBar jMenuBar1;
     private javax.swing.JMenuItem jMenuItem1;
     private javax.swing.JMenuItem jMenuItem2;
     private javax.swing.JMenuItem jMenuItem3;
     private javax.swing.JMenuItem jMenuItem4;
     private javax.swing.JMenuItem jMenuItem5;
     private javax.swing.JMenuItem jMenuItem6;
     private javax.swing.JMenuItem jMenuItem7;
     private javax.swing.JMenuItem jMenuItem8;
     private javax.swing.JMenuItem jMenuItem9;
     private javax.swing.JMenu jmCadastro;
     private javax.swing.JMenuItem jmiGenero;
     // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent e) {
        if (e.getInternalFrame() instanceof CadGenerosGUI) {
            flagCadGenero = false;
        } else if(e.getInternalFrame() instanceof CadJogosGUI){
            flagCadJogo = false;
        } else if(e.getInternalFrame() instanceof AltGenerosGUI){
            flagAltGenero = false;
        } else if(e.getInternalFrame() instanceof CadPlataformasGUI){
             flagCadPlataforma = false;
        } else if(e.getInternalFrame() instanceof AltPlataformasGUI){
             flagAltPlataforma = false;
        } else if(e.getInternalFrame() instanceof CadProdutoraGUI){
             flagCadProdutora = false;
        } else if(e.getInternalFrame() instanceof AltProdutorasGUI){
             flagAltProdutoras = false;
        } else if(e.getInternalFrame() instanceof AltJogosGUI){
             flagAltJogo = false;
        } else if(e.getInternalFrame() instanceof BuscaJogoPlataformaGUI){
             flagJogoPlataforma = false;
        }
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent e) {
        
    }
}
